### ISSUE TITLE
config

### ISSUE THREAD

**Issue by kobrezzzy** [thenikedestroyer/d3stryr-3stripes#13]
i downloaded the config but i cannot open it with anything is their anything you can help with that?

**Comment by thenikedestroyer** [comment]
Open it with any text editor.

**Comment by kobrezzzy** [comment]
also having trouble running the destroyer.py i run the shell and it saying i have no module named settings but i downloaded the requirements txt already. looks like this http://i.imgur.com/y4eRu0S.png
