### ISSUE TITLE
Cannot run d3stryr-3stripes in windows10 please help me

### ISSUE THREAD

**Issue by top1st** [thenikedestroyer/d3stryr-3stripes#15]
i have followed all steps step by step
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Destroyer # c+174 04:45:51.613 [  Page Load Failed   ] Falling back to 2captcha
Traceback (most recent call last):
  File "D:/d3stryr-3stripes-master/destroyer/destroyer.py", line 31, in <module>
    process_add_to_cart(product_info)
  File "D:\d3stryr-3stripes-master\destroyer\cart.py", line 24, in process_add_to_cart
    my_size_ats = product_info['productStock'][my_size]['ATS']
KeyError: '3.5'

Please help me is this captcha code error?
i have valid captcha2 account but i cannot success 
what is major problem
or please provide me nice config.cfg file
why mysize error?

[cart]
masterPid = S31507
mySizes = 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5

please help me

**Comment by thenikedestroyer** [comment]
On vacation for all of 2017. 

Good luck.

**Comment by stussified** [comment]
@top1st from the error, it seems like it doesn't have size 3.5 and is throwing an error.  Just delete 3.5 from mySizes
