### ISSUE TITLE
Error Window : "Google Chrome cannot read and write to its data directory : ChromeTokenHarvestFolder"  

### ISSUE THREAD

**Issue by EncepT** [thenikedestroyer/d3stryr-3stripes#5]
This is the error window i get

Appreciate any help!
![chrome_2016-11-05_19-17-55](https://cloud.githubusercontent.com/assets/20307069/20032573/11fb63ee-a38d-11e6-9730-8c66c7db01fd.png)
![py_2016-11-05_19-21-06](https://cloud.githubusercontent.com/assets/20307069/20032574/181ae376-a38d-11e6-9c43-00d6e1789644.png)

**Comment by thenikedestroyer** [comment]
This isnt an issue with the code. It is an end-user issue. Go ask your question somewhere else.
