### ISSUE TITLE
💩 @THENIKEDESTROYER has to update commit count with every feature 💩

### ISSUE THREAD

**Issue by snuggs** [thenikedestroyer/d3stryr-3stripes#8]
## Problem
Revision count aggregator is not very DRY (https://en.wikipedia.org/wiki/Don't_repeat_yourself).
Currently it's a human _(i.e. @SOLEMARTYR)_

So @thenikedestroyer doesn't have to do this every freaking commit! 😎 
Closes #8 (< autoclose issue when merged)

## Solution
We should use a child process to bring in the commit count into the application
using the following git (porcelain) command.
This will either become a nightmare, or will bit rot until someone takes it out.

```bash
$ git rev-list <branch> --count # More DRY approach
```
Trust me... Been here before...

## References
🔗 Git (porcelain) man page - https://git-scm.com/docs/git-rev-list
🔗 _SHA hash introducing DIFF to codebase_   https://github.com/thenikedestroyer/d3stryr-3stripes/commit/1855e8dd3f2b303b2dc23b59fa0d558167c26e7d

Pull Request on deck...

**Comment by thenikedestroyer** [comment]
As long as I don't have to add any new features or modules.

**Comment by snuggs** [comment]
@thenikedestroyer Bruh... I actually write code remember? 👓 :nerd_face:  No introduction of modules except for core. ❤️ 

PR complete #9

**Comment by thenikedestroyer** [comment]
Looks like it requires the end-user to have git installed.  Already a pain to get them to get python and php right.

**Comment by snuggs** [comment]
@thenikedestroyer I see... I would assume anyone using git would have git installed. Rarely know of people who download zips. And if so should encourage them to use git. Or they'll never be able to contribute pull requests (except for editing on github which is a bore).

Do remember the intent is to push these kids to code #amIRight? 

That said if you'd like to continue updating every revision then by all means. But at LEAST use the same code (on your dev box) to autogenerate the revision file on a commit hook for a push to github. I do it in my node apps. git push -> (commit hook holds push) -> generates revision -> commits revision -> (actually pushes with version bump ✊  commit).

Bumping revisions on each feature gets old around 30+ iterations.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

Ping me if we should close PR #9 kind sir. 

✌️ Snuggs

**Comment by thenikedestroyer** [comment]
Lets close PR #9. 

I don't push via git to avoid accidentally pushing as myself.  And yes, the goal is to get the kids to consider coding - but I almost guarantee you that if you add GIT as an overhead to the code they will lose interest quickly. The benefit of these software versioning tools will have to come at a later time.

**Comment by snuggs** [comment]
ok kewl bro. Manual versioning it is. I'd keep the following script handy at least for yourself tho. ;-)
```bash
$ git rev-list <branch> --count # More DRY approach
```

**Comment by snuggs** [comment]
@thenikedestroyer ping me if there's anything else I can help contribute to cleaning up. Automated tests, etc. I'll be perusing on my own for low hanging fruit as well.

#salute

**Comment by thenikedestroyer** [comment]
Thank you for your effort & suggestion.
